@include('templates.partials.header')
@include('templates.partials.navbar')
@include('templates.partials.sidebar')
@include('templates.partials.breadcumb')
@yield('content')
@include('templates.partials.footer')
